server:
  port: 8848
  servlet:
    context-path: /car-booking
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://113.31.117.118:13306/car_rental
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.yomean.carbooking.bean
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
logging:
  level:
    com:
      yomean:
        carbooking:
          dao: debug
